### ISSUE TITLE
Congratulations for the Project - Doubt with Circles

### ISSUE THREAD

**Issue by gusilveiramp** [surialabs/react-native-geo-fencing#6]
Hello, I am testing with React Native 0.49 and everything is working perfectly, I just needed to make some adjustments on the installation, but after deleting some folders everything worked fine.

My question is about Circles. I intend to create circles and send alerts to the user when he enters the circle. Maybe this is a beginner's doubt, but I really do not know how to do this. Is it possible to create circles instead of polygons with this library?

**Comment by greghaygood** [comment]
The library itself doesn't support circles, since the underlying native code (iOS at least) doesn't directly support it. You can approximate it with a library like this, though: https://www.npmjs.com/package/circle-to-polygon
